services:
  rvgrt-backend:
    build: .
    image: rvgrt-base:latest
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=development
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - web-proxy
      - default

  rvgrt-logger:
    build: .
    image: rvgrt-base:latest
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=development
      - FASTAPI_URL=http://rvgrt-backend:8000
    command: >
      bash -c "uv run python src/logger_admin/manage.py collectstatic --noinput &&
      uv run uvicorn logger_admin.asgi:application --host 0.0.0.0 --port 8001 --app-dir src/logger_admin"
    depends_on:
      - rvgrt-backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - web-proxy
      - default

networks:
  web-proxy:
    external: true